-- Supabase Migration: Scans and Findings Tables
-- Created: 2026-03-05
-- Purpose: Persistent storage for DAST/SAST scan results

-- 1. Scans Table
CREATE TABLE IF NOT EXISTS public.scans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    target_url TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    scan_type TEXT DEFAULT 'full',
    result_summary JSONB DEFAULT '{}'::jsonb,
    scan_logs JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE
);

-- 2. Findings Table
CREATE TABLE IF NOT EXISTS public.findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id UUID REFERENCES public.scans(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    severity TEXT NOT NULL,
    description TEXT,
    remediation TEXT,
    evidence TEXT,
    reproduction_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Row Level Security (RLS)
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.findings ENABLE ROW LEVEL SECURITY;

-- 4. Policies (Allow Anon access for development/demo)
CREATE POLICY "Allow anon read scans" ON public.scans FOR SELECT USING (true);
CREATE POLICY "Allow anon insert scans" ON public.scans FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update scans" ON public.scans FOR UPDATE USING (true);
CREATE POLICY "Allow anon delete scans" ON public.scans FOR DELETE USING (true);

CREATE POLICY "Allow anon read findings" ON public.findings FOR SELECT USING (true);
CREATE POLICY "Allow anon insert findings" ON public.findings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update findings" ON public.findings FOR UPDATE USING (true);
CREATE POLICY "Allow anon delete findings" ON public.findings FOR DELETE USING (true);

-- 5. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_findings_scan_id ON public.findings(scan_id);
CREATE INDEX IF NOT EXISTS idx_scans_created_at ON public.scans(created_at DESC);
